
export const CONSUMER_KEY = '4mHbWoxb3JzcfIFUyjDlyJL6h';

export const SECRET_KEY = 'EJa6iru09FRUVHpI7XRcR4m1DX0XSlZIapxTZLoRabqCIUwgFF';

export const BEARER_TOKEN ='AAAAAAAAAAAAAAAAAAAAAMQL%2BAAAAAAAOZVd9ROoyKKWxmET%2FkCxS8aqrrw%3DhgbkeyZVPR7P6VtVhaY4mx25Y9aZ88jteTj3fu31vlCJURej8T';